base_packages:
  - ca-certificates
  - gnupg
  - lsb-release
  - atop
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

deploy_user: deploy

docker_users:
  - ansible
  - "{{ deploy_user }}"
