- name: Установка зависимостей
  apt: 
    name: "{{ base_packages }}"
    state: present
    update_cache: yes
- name: Добавление Docker ключа
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавление репозитория Докера
  apt_repository:
    repo:  "deb [arch=amd64 ] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release}} stable"
    state: present

- name: Установка Docker
  apt:
     name: "{{ docker_packages }}"
     state: present
     update_cache: yes

- name: Автозапуск Docker
  systemd: 
    name: docker
    enabled: true
    state: started

- name: Добавление докер пользователей в группу
  user:
    name: "{{ item  }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
